In [2]:
import numpy as np

In [9]:
h = np.arange(5)

h

array([0, 1, 2, 3, 4])

In [10]:
w = np.arange(3)

w

array([0, 1, 2])

In [12]:
grid = np.meshgrid(
  w,
  h,
)

grid

[array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])]

In [13]:
grid = np.stack(grid, axis = 0)

grid

array([[[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]],

       [[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]]])